/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class CardiganSystemActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
    
    // Para personagens, calcular o movimento base baseado em Destreza
    // Isso deve ser feito aqui (prepareBaseData) para que ActiveEffects
    // possam adicionar bônus ao valor base
    if (this.type === 'character') {
      const dexterity = this.system.abilities?.dexterity?.value ?? 0;
      const dexterityBonus = this.system.abilities?.dexterity?.bonus ?? 0;
      const totalDexterity = dexterity + dexterityBonus;
      
      // Calcular movimento base: a cada 2 pontos de Destreza = +1 movimento
      const baseMovement = Math.floor(totalDexterity / 2);
      this.system.details.movement = baseMovement;
    }
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.cardigan || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }
}
