import BaseEffect from '../base-effect.mjs';

/**
 * Toxicidade Effect
 * Automatically applies Inconsciente・Sono and Intoxicado effects when toxicity reaches level 5
 * Effects are removed automatically when toxicity drops below 5
 */
export class ToxicidadeEffect extends BaseEffect {
  static effectName = 'Toxicidade';
  static compendiumName = 'cardigan.efeitos-cardigan';
  static _syncInProgress = new Set(); // Track actors being synced to prevent concurrent operations

  /**
   * Synchronize toxicity effects based on toxicity level
   * Adds Inconsciente・Sono and Intoxicado effects when toxicity === 5
   * Removes them when toxicity < 5
   * @param {Actor} actor - The actor to sync effects for
   * @param {number} toxicityLevel - The current toxicity level (0-5)
   */
  static async syncEffect(actor, toxicityLevel) {
    // Only for characters
    if (actor.type !== 'character') return;

    // Prevent concurrent sync operations on the same actor
    if (this._syncInProgress.has(actor.id)) {
      console.log(`[${this.effectName} Sync] Sync already in progress for ${actor.name}, skipping`);
      return;
    }

    try {
      this._syncInProgress.add(actor.id);

      // Check if should have toxicity effects (level 5 = fatal poisoning)
      const shouldHaveEffects = toxicityLevel === 5;

      // Find existing toxicity effects on actor (marked with flag)
      const existingEffects = actor.effects.filter(effect => 
        effect.flags?.cardigan?.source === "toxicity_level5"
      );

      if (shouldHaveEffects) {
        // Should have effects - add if not present
        if (existingEffects.length === 0) {
          await this._addToxicityEffectsToActor(actor);
        }
      } else {
        // Should not have effects - remove if present
        if (existingEffects.length > 0) {
          const effectIds = existingEffects.map(e => e.id);
          await actor.deleteEmbeddedDocuments('ActiveEffect', effectIds);
          console.log(`[${this.effectName} Sync] Removed toxicity effects from ${actor.name}`);
        }
      }
    } catch (error) {
      console.error(`[${this.effectName} Sync] Error syncing toxicity effects:`, error);
    } finally {
      // Always remove the lock, even if an error occurred
      this._syncInProgress.delete(actor.id);
    }
  }

  /**
   * Add toxicity effects (Inconsciente・Sono and Intoxicado) to the actor
   * @param {Actor} actor - The actor to add effects to
   * @private
   */
  static async _addToxicityEffectsToActor(actor) {
    // Double-check: verify effects don't already exist
    const existingEffects = actor.effects.filter(effect => 
      effect.flags?.cardigan?.source === "toxicity_level5"
    );
    
    if (existingEffects.length > 0) {
      console.log(`[${this.effectName} Sync] Effects already exist on ${actor.name}, skipping add`);
      return;
    }

    // Get effects from compendium
    const pack = game.packs.get(this.compendiumName);
    if (!pack) {
      console.error(`[${this.effectName} Sync] Could not find ${this.compendiumName} compendium`);
      return;
    }

    // Find Inconsciente・Sono and Intoxicado in compendium
    const unconsciousIndex = pack.index.find(e => e.name === "Inconsciente・Sono");
    const intoxicatedIndex = pack.index.find(e => e.name === "Intoxicado");

    if (!unconsciousIndex || !intoxicatedIndex) {
      console.error(`[${this.effectName} Sync] Could not find required effects in compendium`);
      return;
    }

    // Load the full documents
    const unconsciousDoc = await pack.getDocument(unconsciousIndex._id);
    const intoxicatedDoc = await pack.getDocument(intoxicatedIndex._id);

    if (!unconsciousDoc || !intoxicatedDoc) {
      console.error(`[${this.effectName} Sync] Could not load effect documents`);
      return;
    }

    // Create ActiveEffects with toxicity flags
    const effectsData = [
      {
        name: "Inconsciente・Sono",
        img: unconsciousDoc.img || "systems/cardigan/assets/images/effects/effects-negative.webp",
        flags: {
          cardigan: {
            source: "toxicity_level5",
            originalName: unconsciousDoc.name,
            originalId: unconsciousDoc.id,
            autoGenerated: true,
            effectType: "unconscious",
            description: this._generateEffectDescription(unconsciousDoc, "inconsciente"),
            descriptionPlainText: this._generateEffectDescriptionPlainText(unconsciousDoc, "inconsciente")
          }
        },
        disabled: false,
        transfer: false
      },
      {
        name: "Intoxicado",
        img: intoxicatedDoc.img || "systems/cardigan/assets/images/effects/effects-negative.webp",
        flags: {
          cardigan: {
            source: "toxicity_level5",
            originalName: intoxicatedDoc.name,
            originalId: intoxicatedDoc.id,
            autoGenerated: true,
            effectType: "intoxicated",
            description: this._generateEffectDescription(intoxicatedDoc, "intoxicado"),
            descriptionPlainText: this._generateEffectDescriptionPlainText(intoxicatedDoc, "intoxicado")
          }
        },
        disabled: false,
        transfer: false
      }
    ];

    // Add effects to actor
    await actor.createEmbeddedDocuments('ActiveEffect', effectsData);
    console.log(`[${this.effectName} Sync] Added toxicity effects to ${actor.name}`);

    // Send chat message notification
    ChatMessage.create({
      content: `${actor.name}: Efeitos "Inconsciente・Sono" e "Intoxicado" aplicados automaticamente devido ao envenenamento fatal (Toxicidade nível 5).`,
      speaker: ChatMessage.getSpeaker({ actor: actor })
    });
  }

  /**
   * Generate effect description with toxicity cause
   * @param {Item} originalItem - Original item from compendium
   * @param {string} effectType - Type of effect (inconsciente or intoxicado)
   * @returns {string} HTML description
   * @private
   */
  static _generateEffectDescription(originalItem, effectType) {
    const originalDescription = originalItem.system.description || "";
    const cause = "envenenamento fatal (Toxicidade nível 5)";
    
    // Add automatic cause information
    if (originalDescription.includes("</p>")) {
      return originalDescription.replace("</p>", ` <em>(Aplicado automaticamente devido a ${cause})</em></p>`);
    } else if (originalDescription.trim()) {
      return `<p>${originalDescription} <em>(Aplicado automaticamente devido a ${cause})</em></p>`;
    } else {
      return `<p>Efeito ${effectType} aplicado automaticamente devido a ${cause}.</p>`;
    }
  }

  /**
   * Generate plain text description for tooltips
   * @param {Item} originalItem - Original item from compendium
   * @param {string} effectType - Type of effect (inconsciente or intoxicado)
   * @returns {string} Plain text description
   * @private
   */
  static _generateEffectDescriptionPlainText(originalItem, effectType) {
    const originalDescription = originalItem.system.description || "";
    
    // Remove HTML tags
    const plainText = originalDescription.replace(/<[^>]*>/g, '').trim();
    
    if (plainText) {
      return plainText;
    } else {
      return `Efeito ${effectType}.`;
    }
  }

  /**
   * Called when the actor is updated
   * Checks if toxicity status changed and syncs effects accordingly
   * @param {Actor} actor - The actor being updated
   * @param {object} changed - The changed data
   * @param {string} userId - The user who initiated the update
   */
  static async onActorUpdate(actor, changed, userId) {
    // Only run on the user who initiated the update
    if (game.user.id !== userId) return;

    // Check if toxicity status changed
    const toxicityChanged = changed.system?.status?.toxicity !== undefined;

    if (toxicityChanged) {
      // Get current toxicity level (use changed value if updated, otherwise use current value)
      const toxicityLevel = changed.system?.status?.toxicity ?? actor.system.status?.toxicity ?? 0;

      await this.syncEffect(actor, toxicityLevel);
    }
  }
}
